id: I5F9FFF71
legacy_id: P009444
ocr_import_info:
  bdrc_scan_id: W28802
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T04:57:04'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T08:42:32.669430+00:00'
last_modified: 2022-09-02 16:43:40.970167
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W28802
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW28802
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གལ་མདོ།
statistics:
  ocr_word_mean_confidence_index: 0.6969455545726734
  ocr_word_median_confidence_index: 0.75
quality: null
bases:
  I6084:
    source_metadata:
      id: http://purl.bdrc.io/resource/I6084
      total_pages: 634
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I6084.txt
    statistics:
      ocr_word_median_confidence_index: 0.75
      ocr_word_mean_confidence_index: 0.6969455545726734
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
